### ISSUE TITLE
crash on wii games on sd

### ISSUE THREAD

**Issue by arturogakaxy** [Fledge68/WiiFlow_Lite#1] opened 2018-08-26 22:56 UTC
Wii games on sd use to crash on load most of the times with this version and another wiiflow lite versions.

**Comment by gingerbeardman** [comment] 2018-11-23 09:31
Can you please explain the problem in detail?

**Comment by JoelStickney** [comment] 2018-11-23 19:10
Simply, loading Wii backups just doesn’t work. I can’t tell if it’s my Wii, the CIOS, or the Wiiflow Lite Version (I’m using 5.0). 

Using d2x beta 52 for IOS 249 (based on 56), and d2x beta 52 for IOS 250 (based on 57) like the whole community recommends  doesn’t play games from my 2GB SD card at least. I have to try a USB to see if that does it. Or try a larger SD card since maybe it’s just incompatible. Half of the time, it just resets the Wii when I try to run a backup Wii game (GameCube game’s run flawlessly with Nintendont though that doesn’t require a CIOS), but the other half the Wii just freezes and I have to do a hard reset. 

So, my process has been to load different d2x versions (tried v6 on 249 based on 56 which didn’t work, but v53-alt worked based on 57, it ran one of the two games I have loaded on an SD card (and both of those games run perfectly on my USB Drive with my other Wii). I then go into the settings and turn off emulated NAND and try both IOS 249 and 250, till I find one that works. I then, after finding 250 worked for one of the two games, went to settings and “extracted the NAND” to run the game with emulated NAND and it froze again (though maybe that is to be expected since beta 53-alt is less compatible with EmuNAND). So more experimentation is needed here with different devices and CIOSs.

**Comment by gingerbeardman** [comment] 2018-11-23 19:35
I run Wii games just fine from SD on WFL 4.x and 5.x so I'm happy to help you troubleshoot this issue. 

I had a similar issue and I had to set Force IOS = on/yes

If you've done that and it still doesn't get into the game, can you post your WFL ini file?

**Comment by JoelStickney** [comment] 2018-11-25 05:57
I started with a clean install of WiiFlowLite 5.0, deleted EVERYTHING associated with it - re-installed the recommended CIOSs (d2x-beta52 in 249 and 250, with base of 56 and 57 for each) installed. No game loaded with ALL default settings (though I did the change one setting, the directory of where Wii Games were located). It didn't work. I switched to another 16GB SD card to see if it was the hardware. It still didn't work. I even tried your Force IOS setting and it didn't work. This was all tested on real nand and emulated as per the settings. 

So, I deleted all WiiFlow files again and installed WFL 4.4, changed the directory of where Wii Games are located and THEY WORKED. So, I re-installed / upgraded to 5.0 without deleting the files associated with 4.4 and all games refused to work AGAIN. Switched back to 4.4 without deleting any files, and they still didn't work. So, I deleted the INK and wiiflow folder and ran 4.4 again and all games worked. I re-setup all the same settings in 4.4 and it's still working. 5.0 doesn't have anything I need so I'll just stay at 4.4 for now. 

But for plugins, at least, Wii Flow is NOT setting when selecting a game. 

"[PLUGINS]
current_item=SMNE01"

It constantly returns to the beginning (letter A) game when I return to WiiFlow Lite. I didn't have this issue with vanilla WiiFlow either, though I think WiiFlow Lite loads a lot faster so I'm sticking with it if I can fix the non-working "current_item" issue.

I've used two "plugins" (selecting them both) to add Gamecube and Wii games show up next to one another and using the [PLUGINS] list to display them all at once, so maybe that's why? But I never had problems doing so with WiiFlow. Does WiiFlow Lite not expect a "current_item" in plugins to be a Gamecube or Wii game so it defaults to the letter A when returning to WiiFlow despite expecting it to show me the game I last played (whether that's a Gamecube or Wii Game).

**Comment by JoelStickney** [comment] 2018-11-25 06:11
Oh no, I just saw your #18 issue and that it's fixed on 5.0 which doesn't work for me while 4.4 has been flawless. Are you also on 5.0 rn? Or the latest commit version?

**Comment by gingerbeardman** [comment] 2018-11-25 08:29
Yes I'm on 5.0

Did you try turning on the "Force IOS" setting that I suggested?

**Comment by Fledge68** [comment] 2018-11-25 23:55
a couple of things.

1. the plugin issue of always starting on letter A has been addressed by gingerbeardman and i fixed it. it will be in the next release v5.0.1 which i will release soon.

2. just so you know. wii games only use an emunand for gamesaves and wiiflow (lite) its referred to as 'savesnand'. you should only use a savesnand if your real nand is running out of space.

it should also be noted that another user on gbatemp has mentioned that when he uses a savesnand his wii games won't boot. so i'm looking into the issue tomorrow to see if its true and how to fix it.
for now don't use a savesnand and you should be fine.

**Comment by Fledge68** [comment] 2018-11-26 00:46
my test results:
wii games and savesnand on USB - games and saves load no problem.
wii games on USB and savesnand on SD - games and saves load no problem.
note saves nand emulation is set to gamesaves. not Full.

no i did not try a wii game on my SD card. maybe tomorrow with more time. unless someone else can try before me.

**Comment by dekkit** [comment] 2019-04-20 14:59
I'm having this exact same issue (using wii lite v5.0.1).   Using a 16GB SD.  it look's to be caused by how game saves are being read on game load when running by SD.

For me this is occurring on some Wii games  more than others (wii sports is a good example of seeing this issue).  Virtual Console games are generally fine.

Note bootmii was installed as an ios channel on this wii (in case this is relevant).

It doesn't seem to matter what I set my emunand settings (ie full or disable) for this as the game seems to alway write to the real nand (verified in wii data management)

To reproduce the issue:
- goto wii data management
- wii game saves
- delete any existing game save for wii sports
- run wii flow lite (v5.x.x)
- run wii sports  (adjusting for relevant ios, mine was 223)
game will boot and inform user it is creating a SAVE 
- confirm save and play a sub game
- exit to home screen

- load wii flow (again)
- attempt to run wii sports
- wii will crash on load

Sometime it will just black screen, sometimes it will load the 1st quarter of progress bar then crash, sometimes it will show debug /memory dump and crash.

After turning off wii and turning on again (via holding power button), if you attempt to load the game a few times (resetting wii each time it crashes) ...it will eventually load the game and play again. 

Also deleting the save file (wii sports in this case) in wii->data management will also immediately fix the issue.

**Comment by Fledge68** [comment] 2019-04-20 22:41
class 10 is the fastest and best. class 4 are slow.

i highly recommend (instead of cIOS 223) to use d2x cIOS v8 Final with a base of 57 or d2x cIOS v10 beta 52 base of 57. they seem to read/write to SD card better.

**Comment by dekkit** [comment] 2019-04-21 13:05
Excellent thanks for the additional info, I was able to get it to play 4-5+ times in a row without crashing (load,play, exit.... load,play exit) , no crashing after a return from standby mode, and no crashing after a cold boot (ie just powered on).    So its now solved for me on a slow SD card!

What worked for me?
- I was using the 16GB Sandisk, class 4 SD Card  (slower card) - a quick speed check showed it was reading at about 19MB per sec.

COMPLETE a cIOS CHECK
- I checked the Custom IOS (cios) I had installed using the Wii app "d2x cIOS installer" using the following website:
https://sites.google.com/site/completesg/backup-launchers/installation

- I made sure that the following had been installed (by reinstalling them):
cIOS v10 beta52  (using base 56) -> installed into IOS slot 249  
cIOS v10 beta52  (using base 57) -> installed into IOS slot 250
Note: its easier to install these by having your wii connected to the internet (but there is an offline method as well)

- That still didn't fix the issue for me, so I downloaded d2x cIOS v8 Final.zip from here (as mentioned above):  https://sourceforge.net/projects/d2x-cios/
Note - use 7zip to open (otherwise it will say you have a corrupt zip).

- As per the readme of v8, I extracted the  d2x cIOS v8 Final.zip over the top of apps\d2x cIOS installer Note - make sure you have a backup of the original cios installer before doing this step

- I then installed, using the modified d2x cIOS installer:
 d2x cIOS v8 Final (using a base of 57) -> installed this into a free IOS slot 240   
Note: I understand you can use any free slot above 200+ if you already have something in slot 240 (just keep note of what slot you use)


Wii FLOW LITE 
GENERAL SETTINGS
This part took quite a bit of trial and error but here are the settings I used.

- Under Settings (cog icon) go into "Startup settings"  (in v5.1.0, this is on page 2 of the settings)
- The following should be set to:
Force Load cIOS = ON
Force cIOS Revision = 250    *this for me is  cIOS v10 beta52  (using base 57)


PER GAME SETTINGS (in my case Wii Sports)
- The following should be set to (on page 1/5):
IOS = 240 *this for me is  d2x cIOS v8 Final
- The following should be set to (on page 4/5):
NAND EMULATION = OFF


The above steps gave me the most consistent and reliable way of loading via SD using a slow SD card.  So have typed it up in the hope that it will assist others who have this issue and find this ticket  via google.  

I might try and mess around with the emu nand settings later but as this finally works, i might just leave it be!

If anyone else is still having issues after the above, try setting Language = English (optional) /  Video Mode = Game (optional)  for each game.

Dek

**Comment by gingerbeardman** [comment] 2019-04-21 13:24
Did you try just Force cios = on?

**Comment by dekkit** [comment] 2019-04-21 13:53
I'll test it now, as i know i tried a variety of combinations previously.

Just to clear, i'll try force cios = on ... cios = auto     also should i try  leaving game settings default to ios 240? (or leave that to auto as  well?)

**Comment by dekkit** [comment] 2019-04-21 14:18
Now that's it working i tried the following combinations:
- with just force cios = on (ios auto) /  emu nand = off    .... game worked fine after a few repeat loads.
- with force cios = off / emu nand = off    .... game worked fine after a few repeat loads (with game ios settings set to to auto).

.. both settings now seem to be running fine after repeated tests - which is weird ... maybe the above steps cleared out a cache/temp files or some conflict.

**Comment by gingerbeardman** [comment] 2019-04-21 14:39
I agree, earlier in the thread I mentioned that I think force iOS should be on by default.

**Comment by Fledge68** [comment] 2019-04-22 10:35
force cios on by default - noted!

**Closed** 2019-10-16 23:39 UTC

**Comment by TeenTin** [comment] 2020-08-09 02:53
Now, more than a year later.  Is there a method load game in SD with emu nand = saves ?

**Comment by gingerbeardman** [comment] 2020-08-09 08:56
@TeenTin try it and see? also: 

> you should only use a savesnand if your real nand is running out of space.

**Comment by TeenTin** [comment] 2020-08-09 09:06
"you should only use a savesnand if your real nand is running out of space."

Not agree.  I use savesnand because I can take my SD to my friends' Wii to
play my save.

Matt Sephton <notifications@github.com> 於 2020年8月9日 週日 下午4:56寫道：

**Comment by gingerbeardman** [comment] 2020-08-09 09:10
It's not about why you would use it, it's about wether it works correctly, or not, if you use it.

**Comment by TeenTin** [comment] 2020-08-09 09:12
The fact is, I do use it and it does not work correctly.  Thanks.

Matt Sephton <notifications@github.com> 於 2020年8月9日 週日 下午5:10寫道：

**Comment by gingerbeardman** [comment] 2020-08-09 09:15
Exactly! That's what it says above, if you use it it does not work correctly. So: don't use it.

**Comment by TeenTin** [comment] 2020-08-09 09:17
If this function does not work correctly, then it becomes an issue needed
to be fixed right ?

Matt Sephton <notifications@github.com> 於 2020年8月9日 週日 下午5:16寫道：

**Comment by gingerbeardman** [comment] 2020-08-09 09:36
sure, but first we need to understand why it's not working. then, other issues have higher priority because this issue has a workaround (which is don't use it).

**Comment by TeenTin** [comment] 2020-08-09 09:46
I see.  I will wait for the fix patiently.  Thank you very much for your
reply.

Matt Sephton <notifications@github.com> 於 2020年8月9日 週日 下午5:36寫道：
