### ISSUE TITLE
Going to Source Menu does not make previous Source as currently selected if multiple Sources use same plugin

### ISSUE THREAD

**Issue by elmimmo** [Fledge68/WiiFlow_Lite#118] opened 2019-10-05 10:08 UTC
When a Source Menus has several Sources that point to a same plugin, when one returns to the Source Menu, the item that becomes the current one is the first Source that uses that plugin, which is not necessarily the Source item that one is coming back from.

This affects Source Menus that subset games from a same plugin by having several Sources items use the same plugin but force a different categories (for, say, dividing MAME roms by year).

Maybe related to #22

Steps to reproduce:

1.	In source_menu.ini, set two sources that use the same plugin but force a different category, like:

		[BUTTON_7]
		autoboot=
		cat_page=1
		category=6
		image=arcade.png
		image_s=arcade.png
		magic=6d616d41,6d616d42,6d616d43,6d616d44,6d616d45,6d616d46,6d616d47
		source=plugin
		title=Arcade 1995-1999 (MAME)
		
		[BUTTON_8]
		autoboot=
		cat_page=1
		category=7
		image=arcade.png
		image_s=arcade.png
		magic=6d616d41,6d616d42,6d616d43,6d616d44,6d616d45,6d616d46,6d616d47
		source=plugin
		title=Arcade 1999-1994 (MAME)

2.	In WiifLow Lite, go to Source Menu and select either of your newly created Sources.
4.	Go to Categories and disable the forced category so that you can see all games for the associated plugins.
5.	Assign category 6 to some, 7 to others.
6.	Go back to Source menu and select the item Arcade 1999-1994 (MAME). The games you assigned the category 7 to should be listed.
7.	Return to Source Menu.

Expected results:

The current item should be Arcade 1999-1994 (MAME) (i.e., the 2nd item)

Actual results:

The current item is Arcade 1995-1999 (MAME)(i.e., the 1st item)

**Comment by Fledge68** [comment] 2019-10-06 22:20
the problem is you are using the same image for both buttons. wiiflow remembers the last source selected by saving the image filename (image=arcade.png). I guess i figured you wouldn't want to use the same image for more than one source button .

but I have rewrote the code to remember that last source button number instead. I just need to test it. 

in the mean time change the name of one of your images and change image=arcade.png to the new filename.

**Comment by Fledge68** [comment] 2019-10-16 23:25
fixed in latest commit. now wiiflow keeps track of the source menu button. not the image filename.

**Closed by Fledge68** 2019-10-16 23:25 UTC
