### ISSUE TITLE
Excite Truck gives black screen when launched from from SD card

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#331] opened 2022-12-28 16:54 UTC
**Describe the bug**

- Excite Truck gives black screen when launched from from SD card.
- works fine from USB

_This is more of a note to prompt investigation rather than a bug report or feature request._

**To Reproduce**
1. No USB, only SD card
1. Launch Excite Truck from SD card

**What version of WiiFlow Lite**
- v5.5.3

**On Wii or Wii U vWii**
- Wii

**Additional context**
- https://gbatemp.net/threads/wiiflow-lite.422685/post-10035102
- https://gbatemp.net/threads/excite-truck-issues.539468/
- https://www.reddit.com/r/WiiHacks/comments/5x9tyg/wiiflow_excite_truck_black_screen/
- https://www.reddit.com/r/WiiHacks/comments/gruxa9/black_screen_on_usb_loader_gx_and_wii_flow/
- https://www.reddit.com/r/WiiHacks/comments/ffp80w/excite_truck_black_screen_at_startup_with_usb/

Also does not work with:
- USB Loader GX v3.0 r1271
- Config USB Loader v70r78.11

**Comment by TeenTin** [comment] 2023-01-15 11:28
Can the newly released cIOS d2x v11 fix the problem ?

**Comment by gingerbeardman** [comment] 2023-01-15 11:42
Feel free to try, I won't have time for a day or two.

**Comment by wiidev** [comment] 2023-01-15 18:46
> Can the newly released cIOS d2x v11 fix the problem ?

It doesn't.

Excite Truck wants access to your SD card, but the d2x cIOS doesn't allow games to read from an SD card while a game is being played from your SD card. That's why it freezes.

**Comment by TeenTin** [comment] 2023-01-15 21:20
> 

I see.  The same with the Kirby in SD problem ?

**Comment by TeenTin** [comment] 2023-01-15 21:21
> I see. The same with the Kirby in SD problem ?



> Excite Truck wants access to your SD card, but the d2x cIOS doesn't allow games to read from an SD card while a game is being played from your SD card. That's why it freezes.

I see.  The same with the Kirby in SD problem ?

**Comment by wiidev** [comment] 2023-01-15 21:31
> I see. The same with the Kirby in SD problem ?

It's playable with the new version USB Loader GX, although some people might experience issues when playing from an SD card. It works perfectly for me though.

**Comment by TeenTin** [comment] 2023-01-15 21:36
> It's playable with the new version USB Loader GX, although some people might experience issues when playing from an SD card. It works perfectly for me though.

Thank you.  I will try the USB Loader GX then.  Hopefully, WiiFlow Lite will be updated to solve this problem (Kirby in SD) in the near future.

**Comment by gingerbeardman** [comment] 2023-01-16 01:48
> It's playable with the new version USB Loader GX

Just Kirby, or Excite Truck too?

**Comment by wiidev** [comment] 2023-01-16 02:42
> Just Kirby, or Excite Truck too?

Excite Truck from USB and Kirby from both.

Excite Truck won't playable from an SD card until changes are made to the d2x cIOS.

**Comment by wiidev** [comment] 2023-01-16 06:40
> Just Kirby, or Excite Truck too?

Excite Truck from USB and Kirby from both.

Excite Truck won't be playable from an SD card until changes are made to the d2x cIOS.

**Comment by gingerbeardman** [comment] 2023-01-16 19:27
Thanks! I'll leave this open for now then.

Should I post an issue on your d2x CIOS repo?

**Comment by wiidev** [comment] 2023-01-16 20:24
> Should I post an issue on your d2x CIOS repo?

I don't have issue reports enabled since I don't want to deal with "my USB flash drive doesn't work" type reports. But I'm fully aware of the read/write SD card issue anyway, so it's okay.

By the way, Kirby isn't fixed by the d2x cIOS update. It works in USB Loader GX because I included patches for the game.

**Comment by TeenTin** [comment] 2023-01-17 04:53
> By the way, Kirby isn't fixed by the d2x cIOS update. It works in USB Loader GX because I included patches for the game.

Hopefully, WiiFlow Lite may do the same.

**Comment by Fledge68** [comment] 2023-03-12 22:53
funny i thought even with the gameconfig patches kirby still freezes during cutscenes when played from SD?

**Comment by Fledge68** [comment] 2023-03-17 20:56
@gingerbeardman i added the usbloadergx kirby patches to wiiflow. I tested and it seems to work but i did have the game freeze when i had a invicibilty cheat applied. other cheats seem to be working. would you be willing to test it?

**Comment by gingerbeardman** [comment] 2023-03-17 20:57
Sure I can test it this weekend. Let me know which binary to try.

**Comment by TeenTin** [comment] 2023-03-17 20:59
Sure !  I am very happy to have the chance to test it !!!

Fledge68 ***@***.***> 於 2023年3月18日 週六 上午4:57寫道：

**Comment by Fledge68** [comment] 2023-03-17 21:33
ok committed. you MUST backup apps/wiiflow and wiiflow/settings folders. the new commits make changes to categories and gamecfg1 ini's.

download - https://github.com/Fledge68/WiiFlow_Lite/suites/11643253919/artifacts/604506238

seems to work for me but some cheats cause freezes. might be my cheat file. oh and cheats menu is a little weird but works. ill fix it soon.

**Comment by TeenTin** [comment] 2023-03-18 00:13
@Fledge68 Tested.  The game loaded.  But when I tried to start by pressing the "Empty" slot, I got a black screen and the system freezed.

**Comment by Fledge68** [comment] 2023-03-19 20:25
@TeenTin thanks for testing. was that it? you only tried one time?  did you have any cheats applied?  did you replace the bins in the bins folder?

@gingerbeardman did you have a chance to try it?

**Comment by TeenTin** [comment] 2023-03-19 20:55
@Fledge68 I have tried at least 6 times.  Ocarina was disabled (i.e. no cheats applied).  I have replaced all the files, including all the bins.  Though the game freezed when starting from an "Empty" slot (i.e. creating a new save), the game can start from an old save (which was created when playing the game with USB drive).

P.S. I found that the categories function is broken.

**Comment by Fledge68** [comment] 2023-03-19 21:05
are you trying to play kirby from SD? because it won't work from SD no matter what.

**Comment by TeenTin** [comment] 2023-03-19 21:08
@Fledge68 Yes, I played kirby from SD.  Isn't the new commits supposed to ?

**Comment by Fledge68** [comment] 2023-03-19 21:11
no. the cios will need to be fixed which Blackb0x might be working on. until then the game still freezes when cutscenes try to play unless the game is on USB. the patches just allow you to apply cheats, change the language, turn off deflicker.

**Comment by TeenTin** [comment] 2023-03-19 21:15
@Fledge68 I see.  Since the USB Loader GX can play (claimed) kirby in SD.  So, I have misunderstood that you have done the same to WFL.  Sorry.

**Comment by Fledge68** [comment] 2023-03-19 21:18
i will try usb loader gx to check and see.

so what's the categories problem?  i hope and pray you backed up dev:/wiiflow/settings folder and contents. the new version makes changes to categories_lite.ini so if you need to go back to the old version you need to restore that folder and its contents.

**Comment by TeenTin** [comment] 2023-03-19 21:30
@Fledge68 No worry.  I have followed your suggestion to backup the folders, so that everything can be restored.  The categories problem is that when I open the global categories to put a cross (i.e. "X") to a category, all the games still show up, including those which have been "tick" on THAT category.  However, the function works well in the last WFL release.

**Comment by Fledge68** [comment] 2023-03-19 21:35
i see. something i may have broke. i will have to look into it. are you talking about wii games or plugin emu games?

**Comment by TeenTin** [comment] 2023-03-19 21:37
@Fledge68 Thanks.  I am talking about Wii games.

**Comment by Fledge68** [comment] 2023-03-19 23:19
fixed categories - just commit. thanks for letting me know.

**Comment by TeenTin** [comment] 2023-03-20 00:33
@Fledge68 Nice.  Pity that I don't know how to complie.  In case you have a new compiled build, please let me know so that I can keep on testing.

**Comment by Fledge68** [comment] 2023-03-20 10:39
just click on 'actions' at the top. then choose the top commit or workflow run. then scroll down to see the artifact and click on it.

but it may not work for you. let me know. i think you have to be a member or something.

**Comment by gingerbeardman** [comment] 2023-03-20 15:43
> @gingerbeardman did you have a chance to try it?

Hi!
- I tested it and got the same black screen when trying to start the main game after picking a save slot
- BUT, then I installed a save game with progress (from [GameFAQS](https://gamefaqs.gamespot.com/wii/935607-kirbys-return-to-dream-land/saves)) and that loaded fine and the game was playable
- Then I deleted the save slot and tried again and got the black screen same as when starting from scratch

I don't know the origin of these patches but it might be worth checking if they tested starting without a save game.

Cheers!

**Comment by Fledge68** [comment] 2023-03-20 16:39
new games don't work because they start with a movie cutscene. if you play with a save game long enough that another cutscene will make it freeze.

**Closed** 2023-04-08 21:03 UTC

**Comment by gingerbeardman** [comment] 2023-04-09 00:12
I will open a new issue if Excite Truck is fixed elsewhere or new info comes to light

**Comment by ayuanx** [comment] 2024-06-03 03:14
> > Can the newly released cIOS d2x v11 fix the problem ?
> 
> It doesn't.
> 
> Excite Truck wants access to your SD card, but the d2x cIOS doesn't allow games to read from an SD card while a game is being played from your SD card. That's why it freezes.

@wiidev 
I think the root cause is that those games (Excite Truck, Kirby, etc.) themselves open and close the SD card.

For the open operation, it is fine because SD card is already opened since the game is loaded from SD card; but it is the close operation that causes the freeze. Once the game closes SD card, you won't be able to read any game data from SD card anymore, which is why thoese games freeze during a game save creation when loaded from SD card.

The solution should be simple by adding a reference counter in d2x cIOS. Each open opeartion increases the counter, while each close operation decreases the counter, and SD card won't be closed until the counter reaches 0 after a close operation.
